# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_testing_123:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout PULL|Clone Code
        uses: actions/checkout@v5

      # Runs a single command using the runners shell
      - name: build container
        run: docker build -t web:1.0 -f /opt/actions-runner/_work/cicd_11-30_batch/cicd_11-30_batch/Dockerfile . || true

      - name: Start or create container
        run: |
          if docker ps -a --format '{{.Names}}' | grep -q '^test$'; then
            echo "Container exists, starting it..."
            docker start test
          else
            echo "Container does not exist, creating it..."
            docker run -d \
              -v '/opt/actions-runner/_work/cicd_11-30_batch/cicd_11-30_batch/html:/var/www/html/' \
              --name test \
              -p 80:80 \
              web:1.0
          fi